### ISSUE TITLE
Cura 5

### ISSUE THREAD

**Issue by Ank164** [lokster/cura-custom-supports#15]
Will this be updated any time soon for cura 5?

Thanks

**Comment by lokster** [comment]
Since Cura devs dropped support for Ubuntu 18.04 (which is my primary OS) with some silly excuse, and I have no intention of upgrading soon - no, unless there is a good reason to waste my time on this.

**Comment by Ank164** [comment]
Well that stinks.  I mean, you are on an old version. 20 works fine.

**Comment by lokster** [comment]
22.04 is way too buggy for me currently (especially the Kubuntu flavor, which I use), 20.04 can already be considered "old" by some (just 3 years of standard support left and makes no sense to waste time upgrading to it), so I stick with what's stable and works best for me - that is 18.04.
Because honestly, trying Kubuntu 22.04 felt like I was 20 years back in the past - literally greeted by a crash after logging in, so... thanks, I'll wait :D
I don't get it why the Cura devs were so eager to switch to Qt6. This was their excuse to not provide backward compatibility with older Ubuntu versions.
Anyway, this is the situation.
