### ISSUE TITLE
Cura 4.6.1: No G-Code created for Custom Supports

### ISSUE THREAD

**Issue by reibuehl** [lokster/cura-custom-supports#9]
I have created some custom support blocks in Cura 4.6.1 but neither in the Cura internal preview nor in an external g-code viewer I see any custom support. 
![MissingCustomSupport](https://user-images.githubusercontent.com/4268514/85170206-5bd3ad80-b26d-11ea-8e08-a0790a85cc3b.JPG)
The picture shows the preview with the custom support block selected but no generated support.

**Comment by mocart2** [comment]
+1

**Comment by lokster** [comment]
Can you save the project as .3mf file and attach it here? I have to check if it's settings related (most likely it's cura bug). Everything works fine for me with Custom FFF Printer.

**Comment by reibuehl** [comment]
Attached is the model from the screenshot as .3mf file.

[MiddleSection.zip](https://github.com/lokster/cura-custom-supports/files/4842422/MiddleSection.zip)

**Comment by lokster** [comment]
The problem is in your settings, because the custom supports use the same settings as the "normal" supports, and you have selected "Touching Buildplate" in "Support Placement".
Just enable "Generate Support" temporarily, set "Support Placement" to "Everywhere", and then uncheck "Generate Support" again.
It will work now.

**Comment by reibuehl** [comment]
Yes, with support everywhere it works. Thanks for checking and explaining this!
